### ISSUE TITLE
Cannot read property 'defaultEncoding' of undefined

### ISSUE THREAD

**Issue by sleeperss** [joelspadin-garmin/vscode-private-extension-manager#60]
Fetching extension updates leads to this error after Code reload and so the loader spinner spin forever.

Whats strange is that, everything works fine with a fresh install of the extension, May be a cache issue ?

Console log :
[2021-09-16 00:36:34.462] [renderer1] [error] Cannot read property 'defaultEncoding' of undefined: TypeError: Cannot read property 'defaultEncoding' of undefined
    at v.Writable.write (internal/streams/writable.js:266:24)
    at Transform.ondata (internal/streams/readable.js:719:22)
    at Transform.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Transform.Readable.push (internal/streams/readable.js:223:10)
    at Transform.push (internal/streams/transform.js:166:32)
    at Transform.afterTransform (internal/streams/transform.js:101:10)
    at Transform.transform [as _transform] (/home/agarcin/.vscode-server/extensions/garmin.private-extension-manager-1.7.0/dist/extension.js:4:610389)
    at Transform._read (internal/streams/transform.js:205:10)
    at Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Transform.Writable.write (internal/streams/writable.js:303:10)
    at PassThrough.ondata (internal/streams/readable.js:719:22)
    at PassThrough.emit (events.js:315:20)
    at PassThrough.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    
   thanks

**Comment by sleeperss** [comment]
After an extension bisect, it appears that its a conflict with vsliveshare-audio...
